### ISSUE TITLE
Add support for filters on trace sessions

### ISSUE THREAD

**Issue by davidwallen** [apigeecs/apigee-perf-summary#3]
The enterprise UI allows for users to filter proxy requests for trace. This is not documented in the the public API for debug sessions. Add support once Apigee adds documentation/support for filtering on the API call.

**Comment by davidwallen** [comment]
Information from Apigee docs team (online docs to be updated soon):

The filters are specified as query parametersyou create a debug session, so should be added to the call from this page: http://docs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/apis/%7Bapi_name%7D/revisions/%7Brevision_number%7D/debugsessions

For headers:

header_<url encoded header name>=<url encoded value>

For query params

qparam_<url encoded query param name>=<url encoded query param value>

For query params, the value is optional; for header params the value is required.

So if you want to filter on the header param Accept, and on the query param pagination, you could:

https://api.enterprise.apigee.com/v1/organizations/charles3/environments/{env_name}/apis/{api_name}/revisions/{revision_number}/debugsessions?session=<sessionid>&header_Accept=application/json&qparam_pagination=true

**Comment by kravinderreddy** [comment]
Hi
This performance tool trying to install on windows7 machine and followed all the steps but some how couldnt able and ran into the following issues.
C:\Users\AppData\Roaming\npm\node_modules\apigee-perf-summary\node_modu
les\iconv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node
_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebu
ild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformTo
olsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 w
as not found. Install the required version of Windows SDK or change the SDK ver
sion in the project property pages or by right-clicking the solution and select
ing "Retarget solution". [C:\Users\AppData\Roaming\npm\node_modules\ap
igee-perf-summary\node_modules\iconv\build\iconv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AppData\Roaming\npm\node_modules\apigee-perf-summ
ary\node_modules\iconv
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "." "-g"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\view\apigee-perf-summary-master\package\npm-debug.log
npm ERR! code 1
